collections:
  - name: community.aws
  - name: community.general
  - name: git+https://github.com/luckslovez/caos-ansible-roles#/caos.ansible_roles/
    type: git
roles:
  - name: andrewrothstein.gh
    version: v0.2.0
