collections:
  - name: community.aws
  - name: ansible.windows
    version: 1.14.0
  - name: ansible.utils
    version: 2.11.0
  - name: chocolatey.chocolatey
    version: 1.5.2
  - name: git+https://github.com/luckslovez/caos-ansible-roles#/caos.ansible_roles/
    type: git

roles:
  - name: morgangraphics.ansible_role_nvm
    version: v2.0.0
  - name: newrelic.newrelic_install
    version: v0.6.0
  - name: andrewrothstein.gh
    version: v0.2.0
