collections:
  - name: community.aws
    # Fixes https://github.com/ansible-collections/community.aws/pull/558
    version: 6.3.0
  - name: ansible.windows
    version: 1.14.0
  - name: ansible.utils
    version: 2.11.0
  - name: chocolatey.chocolatey
    version: 1.5.1
  - name: git+https://github.com/luckslovez/caos-ansible-roles.git#/caos.ansible_roles/
    type: git

roles:
  - name: morgangraphics.ansible_role_nvm
    version: v1.5.2
  - name: newrelic.newrelic_install
    version: v0.6.0
  - name: andrewrothstein.gh
    version: v0.2.0
