collections:
  - name: community.aws
    # Fixes https://github.com/ansible-collections/community.aws/pull/558
    version: 6.3.0
  - name: ansible.windows
    version: 1.14.0
  - name: ansible.utils
    version: 2.11.0

roles:
  - name: morgangraphics.ansible_role_nvm
    version: v1.5.2
  - name: newrelic.newrelic_install
    version: v0.6.0
