fb_package_url: "https://github.com/newrelic/fluent-bit-package/releases/download/{{ gh_prerelease_tag }}/{{ fb_package_name }}"
infra_agent_config_file_absolute_path: C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml
nr_fb_output_file_extension: 'dll'
nr_fb_output_plugin_artifact: 'out_newrelic-windows-{{ plugin_arch }}-{{ plugin_version }}.{{ nr_fb_output_file_extension }}'
nr_fb_output_plugin_url: "https://github.com/newrelic/newrelic-fluent-bit-output/releases/download/v{{ plugin_version }}/{{ nr_fb_output_plugin_artifact }}"
nr_fb_output_plugin_download_file_path: 'C:\Windows\Temp\out_newrelic.{{ nr_fb_output_file_extension }}'