name: Staged release publish for Linux

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
      schema:
        description: 'Schema to be released'
        required: true
        options:
          - fb-amazonlinux
          - fb-centos
          - fb-debian
          - fb-sles
          - fb-ubuntu

env:
  TAG: ${{ github.event.inputs.tag }}
  GPG_MAIL: ${{ secrets.LOGGING_GPG_MAIL }}
  GPG_PASSPHRASE: ${{ secrets.OHAI_GPG_PASSPHRASE }}
  GPG_PRIVATE_KEY_BASE64: ${{ secrets.OHAI_GPG_PRIVATE_KEY_BASE64 }} # base64 encoded
  AWS_S3_BUCKET_NAME: "nr-downloads-main"
  AWS_S3_LOCK_BUCKET_NAME: "onhost-ci-lock"
  AWS_REGION: "us-east-1"
  FB_PACKAGE_NAME: ${{ startsWith(github.event.release.tag_name, '1') && 'td-agent-bit' || 'fluent-bit' }}

jobs:
  publishing-to-s3-linux:
    name: Publish linux artifacts into s3 production bucket
    runs-on: ubuntu-20.04

    steps:
      - name: Publish ${{ github.event.inputs.schema }} to S3 action
        uses: newrelic/infrastructure-publish-action@v1.2.3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OHAI_AWS_ACCESS_KEY_ID_PRODUCTION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OHAI_AWS_SECRET_ACCESS_KEY_PRODUCTION }}
          AWS_ROLE_ARN: ${{ secrets.OHAI_AWS_ROLE_ARN_PRODUCTION }}
          AWS_ROLE_SESSION_NAME: ${{ secrets.OHAI_AWS_ROLE_SESSION_NAME_PRODUCTION }}
        with:
          tag: ${{env.TAG}}
          app_name: ${{env.FB_PACKAGE_NAME}}
          repo_name: "newrelic/fluent-bit-package"
          schema: "custom"
          schema_url: "https://raw.githubusercontent.com/newrelic/fluent-bit-package/main/schemas/${{ github.event.inputs.schema }}.yml"
          aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket_name: ${{ env.AWS_S3_BUCKET_NAME }}
          aws_s3_lock_bucket_name: ${{ env.AWS_S3_LOCK_BUCKET_NAME }}
          access_point_host: "production"
          run_id: ${{ github.run_id }}
          aws_region: ${{ env.AWS_REGION }}
          aws_role_session_name: ${{ env.AWS_ROLE_SESSION_NAME }}
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          # used for signing package stuff
          gpg_passphrase: ${{ env.GPG_PASSPHRASE }}
          gpg_private_key_base64: ${{ env.GPG_PRIVATE_KEY_BASE64 }}

  notify:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Send release details to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "releaseUrl": ":github: ${{ github.event.release.html_url }}",
              "releaseName": "${{ github.event.release.name }}",
              "productName": "${{ env.PRODUCT_NAME }}",
              "productUrl": "${{ env.PRODUCT_URL }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PRODUCT_NAME: Fluentbit Linux Packages
          PRODUCT_URL: https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent
